name: <NODE_NAME>
host: localhost
port: 8080
tls_host: <NODE_PUB_IP>
tls_port: 8443
tls_cert: "/etc/flexlb/certs/server.crt"
tls_key: "/etc/flexlb/certs/server.key"
tls_ca_cert: "/etc/flexlb/certs/ca.crt"
tls_client_cert: "/etc/flexlb/certs/client.crt"
tls_client_key: "/etc/flexlb/certs/client.key"
instance_dir: "/etc/flexlb/instance"
watch_interval: 30
log_level: 0
cluster:
  name: "FLEXLB"
  endpoint: "<CLUSTER_PUB_IP>:8443"
  advertize: "<NODE_ADVERTISE_IP>:8001"
  member: "<NODE1_ADVERTISE_IP>:8001,<NODE2_ADVERTISE_IP>:8001,<NODE3_ADVERTISE_IP>:8001"
  secret_key: "1111111111111111"
  probe_interval: 10
  sync_interval: 60
  retransmit_mult: 2
haproxy:
  config_dir: "/etc/flexlb/haproxy"
  pid_dir: "/run/flexlb/haproxy"
  start_timeout: 1
  global:
    daemon: false
    maxconn: 4000
    uid: 1001
    gid: 1001
    log: "/dev/log local5 info"
  defaults:
    mode: "http"
    log: "global"
    options: 
      - tcplog
      - dontlognull
      - abortonclose
    retries: 2
    maxconn: 20000
    timeout:
      http-request: "8s"
      http-keep-alive: "15s"
      check: "6s"
      queue: "25s"
      connect: "10s"
keepalived:
  config_file: "/etc/keepalived/keepalived.conf"
  config_dir: "/etc/flexlb/keepalived"
  pid_file: "/run/keepalived.pid"
  min_virtual_router_id: 1
  max_virtual_router_id: 255
  advert_int: 1
  auth_type: "AH"
  auth_pass: "PaaSw0Rd"
  global_defs:
    router_id: "FLEXLB"
    vrrp_skip_check_adv_addr: true
    vrrp_garp_interval: 0.1
    vrrp_gna_interval: 0.01